[package]
name = "legion_loader"
version = "0.1.0"
edition = "2021"
description = "Bootloader for Legion OS"
authors = ["Soroush Alinia <soroushalinia.wm@gmail.com"]


[dependencies]
uefi = { version = "0.16.0", features = ["exts"] }
uefi-services = "0.13.0"
xmas-elf = "0.8.0"
log = "0.4.17"